# Generated by Django 5.2.3 on 2025-06-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='productcategory',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='productname',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
